Repository seesharktwo/markershtern, pull requests merged in 2022-08, with the labels that each got.

#12 Mongodb
  infrastructure/README.MD
  infrastructure/docker-compose.yml
  infrastructure/scripts/mongo_setup.sh
Labels: merge

#1 Authorization ADR
  doc/adr/AuthorizationADR.md
Labels: merge

#17 Loki
  infrastructure/README.MD
  infrastructure/config/loki.yaml
  infrastructure/config/promtail.yaml
  infrastructure/docker-compose.yml
Labels: merge

#11 Dev product service
  ProductService/.gitignore
  ProductService/ProductService/Configs/KafkaConsumerSettings.cs
  ProductService/ProductService/Configs/ProductStoreDatabaseSettings.cs
  ProductService/ProductService/CustomDeserializers/ProtoDeserializeer.cs
  ProductService/ProductService/Mapper.cs
  ProductService/ProductService/Models/Product.cs
  ProductService/ProductService/ProductContext.cs
  ProductService/ProductService/ProductService.csproj
  ProductService/ProductService/ProductService.sln
  ProductService/ProductService/Program.cs
  ProductService/ProductService/Properties/launchSettings.json
  ProductService/ProductService/ProtoSerializer.cs
  ProductService/ProductService/Protos/CustomTypes/DecimalValue.cs
  ProductService/ProductService/Protos/OrderEvents.proto
  ProductService/ProductService/Protos/decimalValue.proto
  ProductService/ProductService/Protos/productService.proto
  ProductService/ProductService/Services/KafkaConsumerService.cs
  ProductService/ProductService/Services/ProductService.cs
  ProductService/ProductService/Services/ProductServiceGrpc.cs
  ProductService/ProductService/appsettings.json
  ProductService/ProductService/docker-compose.yml
Labels: merge

#23 feat (kowl)
  infrastructure/README.MD
  infrastructure/docker-compose.yml
Labels: merge

#25 Ansible server setup
  .gitignore
  infrastructure/README.MD
  infrastructure/ansible/initial-setup-playbook.yaml
  infrastructure/ansible/inventory.ini.example
  infrastructure/ansible/run.sh
  infrastructure/ansible/users_to_ssh.json
  infrastructure/config/prometheus.yaml
  infrastructure/config/promtail.yaml
  infrastructure/docker-compose.yaml
  infrastructure/scripts/mongo_setup.sh
Labels: merge

#28 fix:Product service
  ProductService/ProductService/ProductService.sln
  ProductService/ProductService/Program.cs
  ProductService/ProductService/Properties/launchSettings.json
  ProductService/ProductService/appsettings.json
  ProductService/ProductService/docker-compose.yml
Labels: curator review

#9 Facade
  .gitignore
  Facade/Facade/Facade.sln
  Facade/Facade/Facade/Facade.csproj
  Facade/Facade/Facade/GrpcServices/GrpcOrderService.cs
  Facade/Facade/Facade/GrpcServices/GrpcProductService.cs
  Facade/Facade/Facade/Mapper/IMapper.cs
  Facade/Facade/Facade/Mapper/Mapper.cs
  Facade/Facade/Facade/Program.cs
  Facade/Facade/Facade/Properties/launchSettings.json
  Facade/Facade/Facade/Protos/CustomTypes/DecimalValue.cs
  Facade/Facade/Facade/ProtosServices/ProducerSerializer.cs
  Facade/Facade/Facade/Services/GetUserID.cs
  Facade/Facade/Facade/Services/OrderService.cs
  Facade/Facade/Facade/Services/ProductService.cs
  Facade/Facade/Facade/Services/UserBriefcaseService.cs
  Facade/Facade/Facade/Startup.cs
  Facade/Facade/Facade/appsettings.Development.json
  Facade/Facade/Facade/appsettings.json
  Protos/ClientProtos/authServiceForClient.proto
  Protos/ClientProtos/briefcaseServiceForClient.proto
  Protos/ClientProtos/orderServiceForClient.proto
  Protos/ClientProtos/productServiceForClient.proto
  Protos/authService.proto
  Protos/briefcaseService.proto
  Protos/decimalValue.proto
  Protos/orderEvents.proto
  Protos/orderService.proto
  Protos/productService.proto
Labels: curator review

#2 CreateBalanceADR
  doc/ADR/Balance ADR.md
Labels: merge

#6 Transact service
  doc/adr/ADR Transact serviceV4.md
Labels: merge

#32 CD
  .github/workflows/deploy.yaml
  infrastructure/cd/Dockerfile
  infrastructure/cd/cd-run-playbook.yaml
Labels: merge

#30 feat: Facade update mapper
  Facade/Facade/Facade/Facade.csproj
  Facade/Facade/Facade/GrpcServices/GrpcOrderService.cs
  Facade/Facade/Facade/GrpcServices/GrpcProductService.cs
  Facade/Facade/Facade/Mapper/IMapper.cs
  Facade/Facade/Facade/Mapper/Mapper.cs
  Facade/Facade/Facade/MapperProfiles/OrderMapperConfigurations.cs
  Facade/Facade/Facade/MapperProfiles/ProductMapperConfiguration.cs
  Facade/Facade/Facade/Startup.cs
Labels: curator review

#31 Create ConfigurationStandartADR
  doc/adr/ConfigurationStandartADR.md
Labels: documentation, team review

#26 Create: New service Balance
  Protos/balanceService.proto
  Protos/enumList.proto
  Protos/eventList.proto
  UserBalanceMicroservice/.gitignore
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice.sln
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/BalanceContext.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/Configs/DatabaseSettings.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/Configs/KafkaSettings.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/CustomDeserializers/ProtoDeserializeer.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/KafkaServices/AdminTopicBuilderService.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/Models/Transact.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/Models/User.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/Program.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/Properties/launchSettings.json
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/Protos/CustomTypes/DecimalValue.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/ProtosServices/ProducerSerializer.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/Services/BalanceOperationService.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/Services/BalanceServiceGrpc.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/Services/KafkaConsumerService.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/Services/ProducerService.cs
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice.csproj
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/appsettings.Development.json
  UserBalanceMicroservice/UserBalanceMicroservice/UserBalanceMicroservice/appsettings.json
Labels: curator review

#33 try
  Protos/ClientProtos/authServiceForClient.proto
  Protos/ClientProtos/balanceServiceForClient.proto
  Protos/ClientProtos/briefcaseServiceForClient.proto
  Protos/ClientProtos/orderServiceForClient.proto
  Protos/ClientProtos/productServiceForClient.proto
  Protos/authService.proto
Labels: developer response required
